id: cvm_cia_aberta_doc_ipe
title: "CVM - Cias Abertas - IPE"
source_dataset_url: "https://dados.cvm.gov.br/dataset/cia_aberta-doc-ipe"
source: cvm_ckan
ckan_package_id: cia_aberta-doc-ipe
dataset_slug: cia_aberta-doc-ipe
bucket_prefix: cvm/cia_aberta_doc_ipe
include_meta: true
