id: cvm_cia_aberta_doc_dfp
title: "CVM - Cias Abertas - DFP"
source_dataset_url: "https://dados.cvm.gov.br/dataset/cia_aberta-doc-dfp"
source: cvm_ckan
ckan_package_id: cia_aberta-doc-dfp
dataset_slug: cia_aberta-doc-dfp
bucket_prefix: cvm/cia_aberta_doc_dfp
include_meta: true
