id: cvm_cia_estrang_cad
title: "CVM - Companhias Estrangeiras - Informação Cadastral"
source_dataset_url: "https://dados.cvm.gov.br/dataset/cia_estrang-cad"
source: cvm_ckan
ckan_package_id: cia_estrang-cad
dataset_slug: cia_estrang-cad
bucket_prefix: cvm/cia_estrang_cad
include_meta: true
