id: cvm_cia_aberta_doc_vlmo
title: "CVM - Cias Abertas - Valores Mobiliários Negociados e Detidos"
source_dataset_url: "https://dados.cvm.gov.br/dataset/cia_aberta-doc-vlmo"
source: cvm_ckan
ckan_package_id: cia_aberta-doc-vlmo
dataset_slug: cia_aberta-doc-vlmo
bucket_prefix: cvm/cia_aberta_doc_vlmo
include_meta: true
