id: cvm_fi_cad_icvm555_hist
title: "CVM - FI - CAD - ICVM 555 Histórico"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fi-cad"
source: cvm_ckan
ckan_package_id: fi-cad
dataset_slug: fi-cad
bucket_prefix: cvm/fi/cad/icvm555_hist
include_meta: true
filename_include:
  - '^(cad_fi_hist|meta_cad_fi)\.zip$'
