id: cvm_fi_cad_registro_fundo_classe
title: "CVM - FI - CAD - Registro de Fundos, Classes e Subclasses"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fi-cad"
source: cvm_ckan
ckan_package_id: fi-cad
dataset_slug: fi-cad
bucket_prefix: cvm/fi/cad/registro_fundo_classe
include_meta: true
filename_include:
  - '^(registro_fundo_classe|meta_registro_fundo_classe)\.zip$'
