id: cvm_fi_doc_lamina
title: "CVM - FI - Lâmina de Informações Essenciais"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fi-doc-lamina"
source: cvm_ckan
ckan_package_id: fi-doc-lamina
dataset_slug: fi-doc-lamina
bucket_prefix: cvm/fi_doc_lamina
include_meta: true
