id: cvm_fi_doc_eventual
title: "CVM - FI - Documentos Eventuais, DFs e Demonstrativos"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fi-doc-eventual"
source: cvm_ckan
ckan_package_id: fi-doc-eventual
dataset_slug: fi-doc-eventual
bucket_prefix: cvm/fi_doc_eventual
include_meta: true
