id: cvm_fii_doc_inf_anual
title: "CVM - FII - Informe Anual Estruturado"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fii-doc-inf_anual"
source: cvm_ckan
ckan_package_id: fii-doc-inf_anual
dataset_slug: fii-doc-inf_anual
bucket_prefix: cvm/fii/doc/inf_anual
include_meta: true
