id: cvm_fii_doc_inf_mensal
title: "CVM - FII - Informe Mensal Estruturado"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fii-doc-inf_mensal"
source: cvm_ckan
ckan_package_id: fii-doc-inf_mensal
dataset_slug: fii-doc-inf_mensal
bucket_prefix: cvm/fii/doc/inf_mensal
include_meta: true
