id: cvm_fip_doc_inf_trimestral
title: "CVM - FIP - Informe Trimestral"
source_dataset_url: "https://dados.cvm.gov.br/dataset/fip-doc-inf_trimestral"
source: cvm_ckan
ckan_package_id: fip-doc-inf_trimestral
dataset_slug: fip-doc-inf_trimestral
bucket_prefix: cvm/fip_doc_inf_trimestral
include_meta: true
