id: cvm_securit_doc_dfin_cri
title: "CVM - Securitizadoras - Demonstrações Financeiras de CRI"
source_dataset_url: "https://dados.cvm.gov.br/dataset/securit-doc-dfin_cri"
source: cvm_ckan
ckan_package_id: securit-doc-dfin_cri
dataset_slug: securit-doc-dfin_cri
bucket_prefix: cvm/securit_doc_dfin_cri
include_meta: true
