id: anp_aquisicao_processamento_e_estudo_de_dados
title: Aquisição, Processamento e Estudo de Dados
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/aquisicao-procedimento-e-estudo-de-dados
bucket_prefix: anp/aquisicao-processamento-e-estudo-de-dados
runner: anp_govbr
