id: anp_blocos_com_fase_exploratoria_encerrada
title: Blocos com Fase Exploratória Encerrada
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/blocos-com-fase-exploratoria-encerrada
bucket_prefix: anp/blocos-com-fase-exploratoria-encerrada
runner: anp_govbr
