id: anp_comercializacao_de_gas_natural
title: Comercialização de Gás Natural
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/comercializacao-de-gas-natural
bucket_prefix: anp/comercializacao-de-gas-natural
runner: anp_govbr
