id: anp_dados_consolidados_de_movimentacao_de_gas_natural_em_gasodutos_de_transporte
title: Movimentação de Gás Natural em Gasodutos de Transporte
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/dados-consolidados-movimentacao-de-gas-natural-em-gasodutos-de-transporte
bucket_prefix: anp/dados-consolidados-de-movimentacao-de-gas-natural-em-gasodutos-de-transporte
runner: anp_govbr
