id: anp_fase_de_exploracao
title: Fase de Exploração
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/fase-exploracao
bucket_prefix: anp/fase-de-exploracao
runner: anp_govbr
