id: anp_processamento_de_petroleo_e_producao_de_derivados
title: Processamento de petróleo e produção de derivados
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/processamento-de-petroleo-e-producao-de-derivados
bucket_prefix: anp/processamento-de-petroleo-e-producao-de-derivados
runner: anp_govbr
