id: anp_producao_de_biocombustiveis
title: Produção de biocombustíveis
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/producao-de-biocombustiveis
bucket_prefix: anp/producao-de-biocombustiveis
runner: anp_govbr
