id: anp_producao_de_petroleo_e_gas_natural_por_estado_e_localizacao
title: Produção de petróleo e gás natural por estado e localização
source_url: https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/producao-de-petroleo-e-gas-natural-por-estado-e-localizacao
bucket_prefix: anp/producao-de-petroleo-e-gas-natural-por-estado-e-localizacao
runner: anp_govbr
