id: oecd_sdd_stes_cli
title: "OECD Data Explorer - Composite Leading Indicator"
protocol: get_api
source_dataset_url: "https://data-explorer.oecd.org/"
bucket_prefix: supranational/oecd/sdd_stes_cli
source_agency: "OECD"
notes: "Consulta SDMX CSV oficial do OECD Data Explorer para o Composite Leading Indicator."
allowed_hosts:
  - data-explorer.oecd.org
  - sdmx.oecd.org
source_license_url: "https://www.oecd.org/termsandconditions/"
geographic_scope: global
temporal_granularity: monthly
dataset_version: latest
profile_mode: headers
resources:
  - title: "Composite leading indicator, all available dimensions, 2023-2025"
    period: "2023-2025"
    filename: oecd_sdd_stes_cli_all_2023_2025.csv
    source_url: "https://sdmx.oecd.org/public/rest/data/OECD.SDD.STES,DSD_STES@DF_CLI/all?startPeriod=2023-01&endPeriod=2025-12&dimensionAtObservation=AllDimensions&format=csvfilewithlabels"
    source_page_url: "https://data-explorer.oecd.org/"
    format: csv
