# .github/workflows/daily_sync.yml
name: Daily Open Data Sync

on:
  workflow_dispatch:
  schedule:
    # 09:00 BRT ~ 12:00 UTC (ajuste se quiser)
    - cron: "0 12 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run sync
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_BUCKET_OPEN_DATA: open-data
        run: |
          forest-pipelines sync cvm_fi_inf_diario --latest-months 12
